form_builder:
    path: /form-builder
    controller: App\Controller\FormBuilderController::newLocationAction

form_builder_separate_type:
    path: /form-builder-type
    controller: App\Controller\FormBuilderController::newLocationSeparateTypeAction

form_processing_new:
    path: /form-processing/new
    controller: App\Controller\FormProcessingController::newAction

form_processing_index:
    path: /form-processing
    controller: App\Controller\FormProcessingController::indexAction

form_validation_new:
    path: /form-validation/new
    controller: App\Controller\FormValidationController::newAction

form_validation_index:
    path: /form-validation
    controller: App\Controller\FormValidationController::indexAction
