version: '3.9'
services:
  ai2-symfony:
    container_name: ai2-symfony-php
    hostname: ai2-symfony-php
    build: ./docker/ai2-symfony/php
    mem_limit: 512m
    volumes:
      - ./:/docker
    ports:
      - "8800:80"

  ai2-node:
    container_name: ai2-node
    hostname: ai2-node
    build: ./docker/ai2-node
    mem_limit: 1024m
    volumes:
      - ./:/docker
