version: '3.9'
services:
  ai2-symfony-php:
    container_name: ai2-symfony-php
    hostname: ai2-symfony-php
    build: ./docker/ai2-symfony/php
    mem_limit: 512m
    volumes:
      - ./:/docker
      - ./source:/var/www/html
    ports:
      - "8800:80"
    links:
      - ai2-symfony-mysql-trivia
      - ai2-symfony-mysql-spa

  ai2-symfony-mysql:
    container_name: ai2-symfony-mysql
    hostname: ai2-symfony-mysql
    image: mariadb:10.3.9
    mem_limit: 128m
    environment:
      MYSQL_DATABASE: doctrine
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: doctrine
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./data/doctrine:/var/lib/mysql
      - ./:/docker
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "38800:3306"

  ai2-symfony-mysql-trivia:
    container_name: ai2-symfony-mysql-trivia
    hostname: ai2-symfony-mysql-trivia
    image: mariadb:10.3.9
    mem_limit: 128m
    environment:
      MYSQL_DATABASE: trivia
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: trivia
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./data/trivia:/var/lib/mysql
      - ./:/docker
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "38801:3306"

  ai2-symfony-mysql-spa:
    container_name: ai2-symfony-mysql-spa
    hostname: ai2-symfony-mysql-spa
    image: mariadb:10.3.9
    mem_limit: 128m
    environment:
      MYSQL_DATABASE: spa
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: spa
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./data/spa:/var/lib/mysql
      - ./:/docker
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "38802:3306"

  ai2-lab-composer-php:
    container_name: ai2-lab-composer-php
    hostname: ai2-lab-composer-php
    build: ./docker/ai2-lab-composer/php
    mem_limit: 512m
    volumes:
      - ./:/docker
      - ./source/lab-composer:/var/www/html
    ports:
      - "8801:80"

  ai2-lab-pogodynka:
    container_name: ai2-lab-pogodynka
    hostname: ai2-lab-pogodynka
    build: ./docker/ai2-pogodynka/php
    mem_limit: 512m
    volumes:
      - ./:/docker
      - ./source/lab-pogodynka:/var/www/html
    ports:
      - "8802:80"

  ai2-node:
    container_name: ai2-node
    hostname: ai2-node
    build: ./docker/ai2-node
    mem_limit: 1024m
    volumes:
      - ./:/docker

  ai2-laravel-php:
    container_name: ai2-laravel-php
    hostname: ai2-laravel-php
    build: ./docker/ai2-laravel/php
    mem_limit: 512m
    volumes:
      - ./:/docker
      - ./source:/var/www/html
    ports:
      - "8803:80"
    links:
      - ai2-laravel-mysql-laravel

  ai2-laravel-mysql-laravel:
    container_name: ai2-laravel-mysql-spa
    hostname: ai2-laravel-mysql-spa
    image: mariadb:10.3.9
    mem_limit: 128m
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./data/laravel:/var/lib/mysql
      - ./:/docker
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "38803:3306"

  ai2-maven:
    container_name: ai2-maven
    hostname: ai2-maven
    build: ./docker/ai2-maven
    mem_limit: 512m
    volumes:
      - ./:/docker
